### ISSUE TITLE
Определения статических функций в заголовках

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#1]
В проекте ark в заголовке `ina_helper.h` внесены определения целой пачки функций.

Все они определены как статические. Это приводит к тому, что в каждом `.c` файле, в который явно или неявно включен `inha_helper.h` появляются определения этих функций. Скорее всего компилятор выбрасывает неиспользуемые функции, но теоретически это приводит к солидному умножению объема кода. Следует перенести весь код из этого заголовка в соответствующий .c  файл.

**Comment by SeresHotes** [comment]
Добавлен .c файл, в который была пермещена реализация этих функций
