### ISSUE TITLE
Отладочная плата под радио может быть улучшена

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#11]
1) В документации к радио рекомендуется не разводить дорожки под ним
2) Если плата в любом случае двуслойная, то имеет смысл одну строну сделать GND полигоном. Это значительно улучшает ситуацию с различными помехами.
3) Поскольку мы не разводим антенную линию по плате - площадку ANT лучше убрать. Иначе она вносит всякие разные емкости и норовит кого-нибудь с кем-нибудь закоротить

**Comment by Mary662** [comment]
Исправлено в 19b0b53fe58126e3f5a1ba1d57a3242d073af633
