### ISSUE TITLE
Светодиод переполюсован

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#12]
На плате BSK5 светодиод-индикатор питания слева от мосфетного ключа подключен _"задом-наперед"_

**Comment by Snork2** [comment]
На многих других платах в аналогичных конструкциях та же шляпа, поэтому внимательнее

**Comment by Mary662** [comment]
Исправлено в 19b0b53fe58126e3f5a1ba1d57a3242d073af633
