### ISSUE TITLE
Резисторы на затворах FS8205A

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#13]
На затворах этих парных транзисторах стоят токоограничивающие резисторы в 10 кОм.

Имхо, это многовато и может повлиять на делитель напряжения, который там часто водится и привести к очень длительным переключениям транзистора между состояниями, что сложно оценить как вообще повлияет на схему (скорее всего никак, но черт его знает).

Предлагаю заменить эти резисторы на 10 Ом

**Comment by Mary662** [comment]
Исправлено в b89dfe900a633f845c76e1b2d3c38695d6a47e56

**Comment by Mary662** [comment]
Исправлено в b89dfe900a633f845c76e1b2d3c38695d6a47e56
