### ISSUE TITLE
c-mavlink не собирается

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#15]
`ERROR: Duplicate message id 11 for SET_MODE (./message_definitions/v1.0/common.xml:4415) also used by ELECTRICAL_STATE (./message_definitions/v1.0/its.xml:16)`

Вот поэтому

**Comment by Snork2** [comment]
Вот тут пишут что каждый диалект аллоцирует для себя свой диапазон сообщений
https://mavlink.io/en/guide/define_xml_element.html#message_id_ranges

Может так и сделаем? скажем у нас будет 50000-51000?

**Comment by Agnus290** [comment]
Я не против.

**Comment by Snork2** [comment]
В таком случае закрыто в f7df10b912861ad174e68ac099f3bc4aafedeac9

**Comment by Snork2** [comment]
Упс на самом деле в c78d4a9f0e05b1dc1165abcb7e05f8d395a34797
