### ISSUE TITLE
На плате БКУ стм32ф4 не подключен к земле

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#2]
Подключен только к питанию.

Это не хорошо

**Comment by Mary662** [comment]
Уже исправила

**Comment by Snork2** [comment]
Частично исправлено в 789fe59295089e38a365a78c69a7d657e276e2cb

VSSA тоже нужно к земле

**Comment by Mary662** [comment]
Исправила

**Comment by Snork2** [comment]
Исправлено в 6a1ba23798146cb67155e7b050735fdd73ac287b
