### ISSUE TITLE
на плате БКУ для стм32ф4 нужна батарейка для RTC

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#3]
Эта батарейка нужна для того, чтобы Данилина система могла помнить время и без GPS.
Так же, возможно имеет смысл скинуть контакт от этой батарейки к GPS, чтобы оно тоже тикало своими RTC часами и не забывало настойки.

Можно использовать часовую батарейку с держалкой, а можно использовать перезаряжаемый ионистр. К нему нужна схема с диодом и резистором для зарядки

Если есть вопросы по батарейке - их можно задавать, например, мне

**Comment by Mary662** [comment]
Как батарейку подключать?

**Comment by Snork2** [comment]
В дискорде рассказал

**Comment by Mary662** [comment]
Добавила

**Comment by Snork2** [comment]
Сделано, не знаю в каком коммите
