### ISSUE TITLE
На плате БКУ пины boot0 и boot1 для стм32ф4 должны быть на земле

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#4]
Иначе он будет грузится черт знает в каких режимах. Когда обе ножки на земле - включается нормальный режим загрузки.

Не допускается введение каких-либо резисторов и емкостей между ножками  boot и землей. Это вызывает страшенные баги при старте контроллера при подаче питания

**Comment by Mary662** [comment]
Тоже исправила

**Comment by Snork2** [comment]
Исправлено в 789fe59295089e38a365a78c69a7d657e276e2cb
