### ISSUE TITLE
На плате БКУ в JTAG колодке для ESP32 нужна еще земля и питание

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#5]
JTAG пробе нужна земля (ну очевидно почему нужна, ну) и питание целевой системы (а это нужно для того, чтобы проба могла выставить соответсвующее напряжение на сигнальных линиях).

Будет удобно (очень), если эти пины будут рядом

**Comment by Mary662** [comment]
И это исправила

**Comment by Snork2** [comment]
Исправлено в 789fe59295089e38a365a78c69a7d657e276e2cb
