### ISSUE TITLE
На плате БКУ какая-то очевидная лажа со сдвиговыми регистрами

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#6]
Я сейчас пойду смотреть даташит на эти регистры, но то что я вижу - ни капельки не похоже на _цепное_ соединение регистров.

Прошу разобраться. По слухам этим занимался Серей, поэтому вешаю ишью на него

**Comment by Mary662** [comment]
На БСК1 сейчас подключено так же

**Comment by Snork2** [comment]
Даташит прочёл. Все правильно. Был не прав, вопрос снимается
