### ISSUE TITLE
На плате БКУ отсутствует линия для сигналов прерываний от ведомых на шине I2C

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#8]
Собственно её нет. А должна быть. Это третья подтянутая к питанию линия, за которую ведомые как за колокольчик будут дергать ESP32, когда им срочно есть что сказать на шине

**Comment by Mary662** [comment]
Куда ее вести?

**Comment by Snork2** [comment]
В чатик вызываются @SeresHotes и @dll31. На какие пины вести прерывание для I2C ведомых?

**Comment by SeresHotes** [comment]
Линия есть. Указанно в таблице как I2C_INT - GPIO18.
