### ISSUE TITLE
Пин для пайки вывода для антенны с футпринта E22 (радио 433) стоит убрать

### ISSUE THREAD

**Issue by Snork2** [CONZERN-ITS/can-cube-sat#9]
Потому что эту линию мы разводить не будем а проблем от этого пина целый вагон. Он создает паразитную емкость со соседями на плате и имеет тендценцию заливаться оловом с соседями

**Comment by Mary662** [comment]
Его уже нет

**Comment by Snork2** [comment]
Great job!
Полагаю исправлено в 789fe59295089e38a365a78c69a7d657e276e2cb
